



POST http://localhost:3000/user
Content-Type: application/json

{
   
    "email": "1@yahoo.com",
    "password": "16290&idhoihioOIi",
    "country": "IN"
}

###

GET  http://localhost:3000/users


###

// add header to this request
POST http://localhost:3000/signin

Content-Type: application/json

{
    "username": "raman@gmail.com",
    "password": "123321"
}


###


